
server:
  port: 8080

spring:
  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    #url: jdbc:h2:tcp://localhost/~/daylog
    url: jdbc:h2:mem:daylog;NON_KEYWORDS=USER
    username: sa
    password:

  jpa:
    open-in-view: true
    hibernate:
      #ddl-auto: update
      ddl-auto: create
      #naming:
      #  physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init-model: always
  data:
    web:
      pageable:
        max-page-size: 2000
        default-page-size: 20
        one-indexed-parameters: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB

  security:
    user:
      name: test
      password: 1234

file:
  path: /Users/harry/Desktop/workspace/upload/

daylog:
  jwt-key: v8up323RprJyfvrYvGCHYZG5jq3vgFg7tkhaJoQhY6U
