### 테스트 요청

#GET http://localhost:8080/foo
#Content-Type: application/json
#Authorization: asdf

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email" : "harypmw1@dev.com",
  "password" : "1234"
}